;drop table `tcrc`.base_badaccount_book
;drop table `tcrc`.base_cash_account
;drop table `tcrc`.base_device_area
;drop table `tcrc`.base_device_brand
;drop table `tcrc`.base_device_fix_type
;drop table `tcrc`.base_device_info
;drop table `tcrc`.base_device_model
;drop table `tcrc`.base_device_provider
;drop table `tcrc`.base_device_type
;drop table `tcrc`.base_org
;drop table `tcrc`.base_resource
;drop table `tcrc`.base_role
;drop table `tcrc`.base_role_resource
;drop table `tcrc`.base_role_user
;drop table `tcrc`.base_seqno
;drop table `tcrc`.base_user
;drop table `tcrc`.fin_account_book
;drop table `tcrc`.fin_cashbox_book
;drop table `tcrc`.fin_cashno
;drop table `tcrc`.fin_cash_account
;drop table `tcrc`.fin_device_counter_book
;drop table `tcrc`.fin_monitor_rule
;drop table `tcrc`.fin_temp_traninfo
;drop table `tcrc`.fin_tran_exception
;drop table `tcrc`.base_system_use_time
;drop table `tcrc`.base_userhandover_log
;drop table `tcrc`.fin_tran_log;